[package]
name = "enclave-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fortanix-vme-abi = { path = "../fortanix-vme-abi" }
nix = "0.22.1"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = { version = "0.11", features = ["std"] }
vsock = "0.2.4"

[dev-dependencies]
fortanix-vme-abi = { path = "../fortanix-vme-abi", features = ["std"]}
