[package]
name = "fortanix-vme-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.1"          # MIT/Apache-2.0
failure_derive = "0.1.1"   # MIT/Apache-2.0
serde_derive = "1.0.84"    # MIT/Apache-2.0
serde = "1.0.84"           # MIT/Apache-2.0
toml = "0.4.10"            # MIT/Apache-2.0
